In [1]:
import numpy as np

Sistema de ecuaciones de 3x3

$\begin{equation*} \begin{matrix} 3x & -y & -z &=1 \\ -x & +3y & +z &=3 \\ 2x & +y & +4z &=7 \end{matrix} \end{equation*}$



In [2]:
#1.-introducir datos de la matriz 
s=np.array([[3,-1,-1,1],[-1,3,1,3],[2,1,4,7]]).astype(np.float32)
#s=np.array([[3,2,4],[5,-4,6]]).astype(np.float32)

# Matriz  D inversa
Di=np.zeros((3,3))
Di[0,0]=1/s[0,0]
Di[1,1]=1/s[1,1]
Di[2,2]=1/s[2,2]
print(Di)

# Matriz  L+U
LU=s[0:3,0:3]
LU[0,0]=0
LU[1,1]=0
LU[2,2]=0
print(LU)

# Matriz  b
b=s[:,3].reshape(3,1)
print(b)

[[0.33333333 0.         0.        ]
 [0.         0.33333333 0.        ]
 [0.         0.         0.25      ]]
[[ 0. -1. -1.]
 [-1.  0.  1.]
 [ 2.  1.  0.]]
[[1.]
 [3.]
 [7.]]


In [6]:
#punto incial
x=np.array([[0],[0],[0]])
for i in range(10):
    x=-Di@LU@x+Di@b
    print(x)
    print("_____")

[[0.33333333]
 [1.        ]
 [1.75      ]]
_____
[[1.25      ]
 [0.52777778]
 [1.33333333]]
_____
[[0.9537037 ]
 [0.97222222]
 [0.99305556]]
_____
[[0.98842593]
 [0.98688272]
 [1.03009259]]
_____
[[1.00565844]
 [0.98611111]
 [1.00906636]]
_____
[[0.99839249]
 [0.99886403]
 [1.000643  ]]
_____
[[0.99983568]
 [0.99924983]
 [1.00108775]]
_____
[[1.00011253]
 [0.99958264]
 [1.0002697 ]]
_____
[[0.99995078]
 [0.99994761]
 [1.00004808]]
_____
[[0.99999856]
 [0.99996757]
 [1.00003771]]
_____
